export default {
  SIGN_UP: 'SIGN_UP',
  LOGIN: 'LOGIN',
  ENGINEER_LOGIN: 'ENGINEER_LOGIN',
  RESET_PASSWORD: 'RESET_PASSWORD',
  UPLOAD_IMAGE: 'UPLOAD_IMAGE',
  REQUEST: 'REQUEST',
  CREATE_REQUEST: 'CREATE_REQUEST',
  UPDATE_REQUEST: 'UPDATE_REQUEST',
  LOAD_REQUEST: ' LOAD_REQUEST',
};
